name: Android CI

on: [push, pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build Application
        run: |
          cd Application
          ../gradlew build --stacktrace
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run unit tests for Application
        run: |
          cd Application
          ../gradlew test --info
  run-instrumented-tests:
    runs-on: macos-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run instrumented tests for Application
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: cd Application && ../gradlew connectedAndroidTest